<template>
  <div id="app">
    <a href="/index.html">
    <img src="./assets/worldmapdots2.png" alt="a silhouette of the world, in dot form" width="40%">
    </a>
    <div id="intro">
      <h1>welcome</h1>
      <h2>I want to read news about...</h2>
      </div>
    <HelloWorld/>
    <div id="belowfold">
    <p>Nah, I wanna check the <a href="http://www.dfoong.com/wats4000-caching-data">weather. </a>(°C)</p>
    <p>
   This website displays top headlines from 54 countries around the world. Sourced from a variety of media outlets (BBC, New York Times, and more). Generated by <a href="https://newsapi.org">News API.</a></p>

   <p>
     欢迎. 这个网站会展示新闻媒体从54国内。我用<a href="https://newsapi.org">NEWS API</a>做的。Bienvenido. Este sitio web mostrará los medios de comunicación de 54 países. 환영합니다.이 웹 사이트는 54 개국의 뉴스 매체를 선보일 것입니다. ようこそ。このウェブサイトは54カ国からのニュースメディアを紹介します。</p>

   <p>built by <a href="https://github.com/dfoong"> Debbie Foong</a> 2018.</p>
    </div>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld'

export default {
  name: 'App',
  components: {
    HelloWorld
  }
}
</script>

<!-- styles here for OVERALL -->
<style>
@import url('https://fonts.googleapis.com/css?family=Noto+Serif');

#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
  }

#belowfold {
  text-align: center;
  padding: 0% 25% 0% 25%;
}

a {
  color:#2f77bc;
}

a:hover {
  color:#e709a0;
}

#myBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: 1px solid black;
  outline: none;
  background-color: #fff23e;
  color: black;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#myBtn:hover {
  background-color: #555;
}

</style>
